### ISSUE TITLE
Strange GSA Link

### ISSUE THREAD

**Issue by fhaverkamp** [open-power/capiflash#4]
```
├── build
│   ├── doxygen
│   │   └── doxygen.conf
│   ├── install
│   │   ├── makefile
│   │   └── resources
│   │       ├── 1410f0041410f004.00000001151029D1 -> /gsa/ausgsa/projects/s/surelock/images/1410f0041410f004.00000001151029D1
│   │       ├── 80-cxl.rules
│   │       ├── 80-cxlflash.rules
```

I guess the GSA link is something which is not supposed to be in the external repository, is it not?

**Comment by robtaylor** [comment]
This image not being available is a critical issue - nothing to load on the AFU!

**Comment by robtaylor** [comment]
@mikehollinger @jayantpatel @vageline

**Comment by mikehollinger** [comment]
Hi guys! Yep - this is one that we knew we'd eventually need to resolve. The build process (which you see here) relies on packaging together the adapter microcode that's supplied by a sub-team. Rather than check in the binaries, we check in a pointer to where those land. In general, however, we don't expect people to build their own adapter microcode images (at this time). This might change in the future; an option for dealing with it would be to declare on invocation of the build, that we will build and package a specific microcode image, supplied by an env var. If that's not specified, the build might only build the software and its test packages?

I dunno - I welcome thoughts on that... we could also just pull the trigger and check in the large-ish blobs of code to the repo.

**Comment by robtaylor** [comment]
Depending on the size an how much it gets changed, you could just commit directly in the reposiorty, or you could use git-lfs https://git-lfs.github.com/

**Comment by vageline** [comment]
There are no longer gsa links in the repo.
